In [1]:
from google import genai
from google.genai.types import EmbedContentConfig
from google.genai import types
import pandas as pd
import time
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

In [2]:
client = genai.Client(vertexai=True, project="resume-radar-thuan", location="us-central1")

In [3]:
bq = bigquery.Client(project="resume-radar-thuan")

In [4]:
df = pd.read_csv('data/postings.csv')
df = df.dropna(subset = ['formatted_experience_level'])
df['text'] = df.title +  ' ' + df.description.fillna("")
X = df.text
y = df.formatted_experience_level
df['text'].str.len().mean()

np.float64(3910.1427996611606)

In [5]:
df_sample = df.sample(n=10000, random_state = 42)

In [6]:
try:
    done = {row.job_id for row in bq.query("SELECT job_id FROM resume_radar.posting_embeddings").result()}
except NotFound:
    done = set()

In [7]:
batch_size = 100

try:
    done = {row.job_id for row in bq.query("SELECT job_id FROM resume_radar.posting_embeddings").result()}
except NotFound:
    done = set()
todo = df_sample[~df_sample["job_id"].isin(done)]
for start in range(0, len(todo), batch_size):
    batch = todo.iloc[start:start +batch_size]
    
    for attempt in range(5):
        try:
            embed_content = client.models.embed_content(
                model="gemini-embedding-001",
                contents=batch.text.to_list(),
                config=types.EmbedContentConfig(output_dimensionality=768),)
            break
        except Exception as e:
            print(f"batch {start}: attempt {attempt} failed: {e}")
            time.sleep(2 ** attempt)
    else:
        raise RuntimeError(f"batch {batch} failed 5 times")
    
    rows = pd.DataFrame({
    "job_id": batch["job_id"].to_list(),
    "embedding": [e.values for e in embed_content.embeddings],
    "model": "gemini-embedding-001-768",
    })
    bq.load_table_from_dataframe(rows, "resume_radar.posting_embeddings").result()
    print(f"done {start + len(batch)} / {len(todo)}")

In [8]:
query = """
WITH target AS (
  SELECT embedding FROM resume_radar.posting_embeddings WHERE job_id = 3905341299
)
SELECT
  p.title,
  p.job_id,
  ML.DISTANCE(target.embedding, o.embedding, 'COSINE') AS cos_dist
FROM resume_radar.posting_embeddings AS o
CROSS JOIN target
JOIN resume_radar.postings AS p ON p.job_id = o.job_id
WHERE o.job_id != 3905341299
ORDER BY cos_dist ASC      
LIMIT 10
"""
for row in bq.query(query).result():
    print(row)

Row(('Web Designer I', 3904402111, 0.21990431061940008), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Data Scientist', 3904363560, 0.23739560201518262), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Senior Data Scientist, Experimentation & Personalization', 3894285749, 0.2495690208598913), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Data Scientist I', 3904960773, 0.26596970265235476), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Data Analytics Consultant', 3900089227, 0.26903815818091936), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Data Scientist Lead – Telematics (Remote)', 3894627680, 0.27370603422463313), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Data Scientist', 3906226694, 0.2812813937142221), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Data Scientist III, Innovation', 3905885501, 0.2866950120680073), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Associate Predictive Modeler II', 3885828791, 0.2899849299257812), {'title': 0, 'job_id': 1, 'cos_dist': 2})
Row(('Senior Data Scientist', 3905828147, 0.2929537450388291), {'title': 0, 'job_id': 1, 'cos_dist': 2})

In [9]:
query = """
SELECT job_id, title FROM resume_radar.postings 
WHERE job_id IN (SELECT job_id FROM resume_radar.posting_embeddings)
AND LOWER(title) LIKE '%data scientist%' LIMIT 5
"""
for row in bq.query(query).result():
    print(row)

Row((3905341299, 'Data Scientist'), {'job_id': 0, 'title': 1})
Row((3904960773, 'Data Scientist I'), {'job_id': 0, 'title': 1})
Row((3885812100, 'junior java programmer/data scientist'), {'job_id': 0, 'title': 1})
Row((3905885501, 'Data Scientist III, Innovation'), {'job_id': 0, 'title': 1})
Row((3902834352, 'Vice President/P&C Actuary/Data Scientist - PR12682'), {'job_id': 0, 'title': 1})

In [84]:
anchors = df_sample.sample(n=10, random_state= 7)[['job_id','title']]
anchors

            job_id                                              title
1894    3884440227  National Team  Manager - Construction Material...
22323   3889711039                        Construction Superintendent
96117   3904942511                                 Accounting Manager
101037  3905239556                                   Python Developer
95373   3904928589  Industry Sales Executive- Communications, Medi...
108109  3905336539                        Families First Case Manager
33468   3895210127              Senior Information Technology Manager
96156   3904942873  Remote Client Services Rep (Insurance) - No Ex...
76391   3903471528                     Combination Building Inspector
42768   3899542292                     Consumer Loan Sales Specialist

In [87]:
sample = []
for job in anchors.itertuples():
    query = f"""
    WITH target AS (
      SELECT e.embedding, e.job_id, p2.title AS anchor_title, p2.company_name AS anchor_company 
      FROM resume_radar.posting_embeddings e 
      JOIN resume_radar.postings p2
      ON p2.job_id = e.job_id
      WHERE e.job_id = {job[1]}
    )
    SELECT
      p.title,
      target.anchor_title,
      target.anchor_company,
      target.job_id,
      p.job_id,
      p.company_name,
      ML.DISTANCE(target.embedding, o.embedding, 'COSINE') AS cos_dist
    FROM resume_radar.posting_embeddings AS o
    CROSS JOIN target
    JOIN resume_radar.postings AS p ON p.job_id = o.job_id
    WHERE o.job_id != {job[1]}
    ORDER BY cos_dist ASC      
    LIMIT 3
    """
    for row in bq.query(query).result():
        sample.append(dict(row))

[{'title': 'National Practice  Manager - Construction Materials Testing', 'anchor_title': 'National Team  Manager - Construction Materials Testing', 'anchor_company': 'Atlas', 'job_id': 3884440227, 'job_id_1': 3884439422, 'company_name': 'Atlas', 'cos_dist': 0.015809860535369813}, {'title': 'Resident Engineer', 'anchor_title': 'National Team  Manager - Construction Materials Testing', 'anchor_company': 'Atlas', 'job_id': 3884440227, 'job_id_1': 3902868071, 'company_name': 'Atlas', 'cos_dist': 0.21449277382558984}, {'title': 'Structural Bridge Engineering Manager #24-170', 'anchor_title': 'National Team  Manager - Construction Materials Testing', 'anchor_company': 'Atlas', 'job_id': 3884440227, 'job_id_1': 3886884354, 'company_name': 'Atlas', 'cos_dist': 0.2176706755484592}, {'title': 'Construction Superintendent', 'anchor_title': 'Construction Superintendent', 'anchor_company': 'Allegiance Technology', 'job_id': 3889711039, 'job_id_1': 3888973746, 'company_name': 'gpac', 'cos_dist': 0.21320896743070838}, {'title': 'Construction Superintendent', 'anchor_title': 'Construction Superintendent', 'anchor_company': 'Allegiance Technology', 'job_id': 3889711039, 'job_id_1': 3900973979, 'company_name': 'RightPro Staffing', 'cos_dist': 0.21633215741922673}, {'title': 'Construction Superintendent', 'anchor_title': 'Construction Superintendent', 'anchor_company': 'Allegiance Technology', 'job_id': 3889711039, 'job_id_1': 3905248917, 'company_name': 'Torque Consulting', 'cos_dist': 0.22243616907634267}, {'title': 'Accounting Manager', 'anchor_title': 'Accounting Manager', 'anchor_company': 'Comprehensive Logistics Co., Inc.', 'job_id': 3904942511, 'job_id_1': 3902835482, 'company_name': 'Ledgent', 'cos_dist': 0.18953827127533296}, {'title': 'Accounting Manager', 'anchor_title': 'Accounting Manager', 'anchor_company': 'Comprehensive Logistics Co., Inc.', 'job_id': 3904942511, 'job_id_1': 3901803465, 'company_name': 'Broadview Federal Credit Union', 'cos_dist': 0.20299654465655692}, {'title': 'Accounting Manager', 'anchor_title': 'Accounting Manager', 'anchor_company': 'Comprehensive Logistics Co., Inc.', 'job_id': 3904942511, 'job_id_1': 3891068832, 'company_name': 'CloudMasters', 'cos_dist': 0.21275995884221954}, {'title': 'Python Developer', 'anchor_title': 'Python Developer', 'anchor_company': 'Digitive', 'job_id': 3905239556, 'job_id_1': 3905341346, 'company_name': 'Radiansys Inc.', 'cos_dist': 0.2581694609852557}, {'title': 'Python Developer with AWS', 'anchor_title': 'Python Developer', 'anchor_company': 'Digitive', 'job_id': 3905239556, 'job_id_1': 3904949263, 'company_name': 'Dice', 'cos_dist': 0.2610304346130866}, {'title': 'Python Software Engineer', 'anchor_title': 'Python Developer', 'anchor_company': 'Digitive', 'job_id': 3905239556, 'job_id_1': 3900967065, 'company_name': 'JPMorgan Chase & Co.', 'cos_dist': 0.2691283503867985}, {'title': 'Oracle NetSuite - Account Executive - GB Central - Mid-market', 'anchor_title': 'Industry Sales Executive- Communications, Media and Entertainment', 'anchor_company': 'Oracle', 'job_id': 3904928589, 'job_id_1': 3901997626, 'company_name': 'NetSuite', 'cos_dist': 0.17404406790286542}, {'title': 'Oracle NetSuite - Account Executive - Corporate - GB Central', 'anchor_title': 'Industry Sales Executive- Communications, Media and Entertainment', 'anchor_company': 'Oracle', 'job_id': 3904928589, 'job_id_1': 3901996683, 'company_name': 'NetSuite', 'cos_dist': 0.17838733792111705}, {'title': 'NetSuite Sales Account Manager - West', 'anchor_title': 'Industry Sales Executive- Communications, Media and Entertainment', 'anchor_company': 'Oracle', 'job_id': 3904928589, 'job_id_1': 3886472127, 'company_name': 'NetSuite', 'cos_dist': 0.19984617060703525}, {'title': 'Behavioral Specialist', 'anchor_title': 'Families First Case Manager', 'anchor_company': 'Samaritas', 'job_id': 3905336539, 'job_id_1': 3905209137, 'company_name': 'Samaritas', 'cos_dist': 0.1988204353392664}, {'title': 'Case Manager, Digital Literacy Learning', 'anchor_title': 'Families First Case Manager', 'anchor_company': 'Samaritas', 'job_id': 3905336539, 'job_id_1': 3894866908, 'company_name': 'Samaritas', 'cos_dist': 0.21238287448978332}, {'title': 'Youth Specialist', 'anchor_title': 'Families First Case Manager', 'anchor_company': 'Samaritas', 'job_id': 3905336539, 'job_id_1': 3906255411, 'company_name': 'Samaritas', 'cos_dist': 0.2598175942225075}, {'title': 'Senior Manager of IT Operations', 'anchor_title': 'Senior Information Technology Manager', 'anchor_company': 'Forty-Five Group', 'job_id': 3895210127, 'job_id_1': 3906256451, 'company_name': 'Stowers Institute for Medical Research', 'cos_dist': 0.25864700147579056}, {'title': 'Information Technology Manager', 'anchor_title': 'Senior Information Technology Manager', 'anchor_company': 'Forty-Five Group', 'job_id': 3895210127, 'job_id_1': 3895207569, 'company_name': 'Risus Talent Partners', 'cos_dist': 0.26225708350424803}, {'title': 'Senior Systems Technician', 'anchor_title': 'Senior Information Technology Manager', 'anchor_company': 'Forty-Five Group', 'job_id': 3895210127, 'job_id_1': 3902350941, 'company_name': 'CTCI Americas Inc', 'cos_dist': 0.2737332429482848}, {'title': 'Entry Level Insurance Sales Agent', 'anchor_title': 'Remote Client Services Rep (Insurance) - No Experience Required', 'anchor_company': 'RemoteWorker US', 'job_id': 3904942873, 'job_id_1': 3901390330, 'company_name': 'Bankers Life', 'cos_dist': 0.27261864109038036}, {'title': 'Customer Service ( Remote work , No Vaccination Required)', 'anchor_title': 'Remote Client Services Rep (Insurance) - No Experience Required', 'anchor_company': 'RemoteWorker US', 'job_id': 3904942873, 'job_id_1': 3889416453, 'company_name': 'Talentify.io', 'cos_dist': 0.28340835032733025}, {'title': 'Insurance Sales Representative', 'anchor_title': 'Remote Client Services Rep (Insurance) - No Experience Required', 'anchor_company': 'RemoteWorker US', 'job_id': 3904942873, 'job_id_1': 3891016423, 'company_name': 'Bankers Life', 'cos_dist': 0.2838669667522371}, {'title': 'Code Compliance Officer I', 'anchor_title': 'Combination Building Inspector', 'anchor_company': 'SAFEbuilt', 'job_id': 3903471528, 'job_id_1': 3887710472, 'company_name': 'Albemarle County', 'cos_dist': 0.3031222434080323}, {'title': 'Construction Inspector II', 'anchor_title': 'Combination Building Inspector', 'anchor_company': 'SAFEbuilt', 'job_id': 3903471528, 'job_id_1': 3901174787, 'company_name': 'KCI Technologies, Inc.', 'cos_dist': 0.3050112681216405}, {'title': 'Utility Inspector II', 'anchor_title': 'Combination Building Inspector', 'anchor_company': 'SAFEbuilt', 'job_id': 3903471528, 'job_id_1': 3895203067, 'company_name': 'Johnson, Mirmiran & Thompson', 'cos_dist': 0.33299450296526745}, {'title': 'Branch Manager Trainee', 'anchor_title': 'Consumer Loan Sales Specialist', 'anchor_company': 'OneMain Financial', 'job_id': 3899542292, 'job_id_1': 3905202067, 'company_name': 'Mariner Finance', 'cos_dist': 0.2750287277326211}, {'title': 'Customer Service Representative- Bilingual Spanish Preferred', 'anchor_title': 'Consumer Loan Sales Specialist', 'anchor_company': 'OneMain Financial', 'job_id': 3899542292, 'job_id_1': 3895800075, 'company_name': 'PLS Financial Services, Inc.', 'cos_dist': 0.27854618651671925}, {'title': 'Customer Service Representative- Bilingual Spanish Preferred', 'anchor_title': 'Consumer Loan Sales Specialist', 'anchor_company': 'OneMain Financial', 'job_id': 3899542292, 'job_id_1': 3888999967, 'company_name': 'PLS Financial Services, Inc.', 'cos_dist': 0.2785461865167198}]

In [92]:
the_list = pd.DataFrame(sample)
the_list['relevant'] = 0

In [102]:
#the_list.to_csv("eval.csv")
the_list_evaluated = pd.read_csv("eval.csv")
the_list_evaluated

,Unnamed: 0,title,anchor_title,anchor_company,job_id,job_id_1,company_name,cos_dist,relevant
0,0,National Practice Manager - Construction Mate...,National Team Manager - Construction Material...,Atlas,3884440227,3884439422,Atlas,0.015810,0
1,1,Resident Engineer,National Team Manager - Construction Material...,Atlas,3884440227,3902868071,Atlas,0.214493,1
2,2,Structural Bridge Engineering Manager #24-170,National Team Manager - Construction Material...,Atlas,3884440227,3886884354,Atlas,0.217671,1
3,3,Construction Superintendent,Construction Superintendent,Allegiance Technology,3889711039,3888973746,gpac,0.213209,1
4,4,Construction Superintendent,Construction Superintendent,Allegiance Technology,3889711039,3900973979,RightPro Staffing,0.216332,1
5,5,Construction Superintendent,Construction Superintendent,Allegiance Technology,3889711039,3905248917,Torque Consulting,0.222436,1
6,6,Accounting Manager,Accounting Manager,"Comprehensive Logistics Co., Inc.",3904942511,3902835482,Ledgent,0.189538,1
7,7,Accounting Manager,Accounting Manager,"Comprehensive Logistics Co., Inc.",3904942511,3901803465,Broadview Federal Credit Union,0.202997,1
8,8,Accounting Manager,Accounting Manager,"Comprehensive Logistics Co., Inc.",3904942511,3891068832,CloudMasters,0.212760,1
9,9,Python Developer,Python Developer,Digitive,3905239556,3905341346,Radiansys Inc.,0.258169,1
10,10,Python Developer with AWS,Python Developer,Digitive,3905239556,3904949263,Dice,0.261030,1
11,11,Python Software Engineer,Python Developer,Digitive,3905239556,3900967065,JPMorgan Chase & Co.,0.269128,1
12,12,Oracle NetSuite - Account Executive - GB Centr...,"Industry Sales Executive- Communications, Medi...",Oracle,3904928589,3901997626,NetSuite,0.174044,1
13,13,Oracle NetSuite - Account Executive - Corporat...,"Industry Sales Executive- Communications, Medi...",Oracle,3904928589,3901996683,NetSuite,0.178387,1
14,14,NetSuite Sales Account Manager - West,"Industry Sales Executive- Communications, Medi...",Oracle,3904928589,3886472127,NetSuite,0.199846,1
15,15,Behavioral Specialist,Families First Case Manager,Samaritas,3905336539,3905209137,Samaritas,0.198820,1
16,16,"Case Manager, Digital Literacy Learning",Families First Case Manager,Samaritas,3905336539,3894866908,Samaritas,0.212383,1
17,17,Youth Specialist,Families First Case Manager,Samaritas,3905336539,3906255411,Samaritas,0.259818,1
18,18,Senior Manager of IT Operations,Senior Information Technology Manager,Forty-Five Group,3895210127,3906256451,Stowers Institute for Medical Research,0.258647,1
19,19,Information Technology Manager,Senior Information Technology Manager,Forty-Five Group,3895210127,3895207569,Risus Talent Partners,0.262257,1
20,20,Senior Systems Technician,Senior Information Technology Manager,Forty-Five Group,3895210127,3902350941,CTCI Americas Inc,0.273733,1
21,21,Entry Level Insurance Sales Agent,Remote Client Services Rep (Insurance) - No Ex...,RemoteWorker US,3904942873,3901390330,Bankers Life,0.272619,1
22,22,"Customer Service ( Remote work , No Vaccinatio...",Remote Client Services Rep (Insurance) - No Ex...,RemoteWorker US,3904942873,3889416453,Talentify.io,0.283408,1
23,23,Insurance Sales Representative,Remote Client Services Rep (Insurance) - No Ex...,RemoteWorker US,3904942873,3891016423,Bankers Life,0.283867,1
24,24,Code Compliance Officer I,Combination Building Inspector,SAFEbuilt,3903471528,3887710472,Albemarle County,0.303122,1
25,25,Construction Inspector II,Combination Building Inspector,SAFEbuilt,3903471528,3901174787,"KCI Technologies, Inc.",0.305011,1
26,26,Utility Inspector II,Combination Building Inspector,SAFEbuilt,3903471528,3895203067,"Johnson, Mirmiran & Thompson",0.332995,1
27,27,Branch Manager Trainee,Consumer Loan Sales Specialist,OneMain Financial,3899542292,3905202067,Mariner Finance,0.275029,0
28,28,Customer Service Representative- Bilingual Spa...,Consumer Loan Sales Specialist,OneMain Financial,3899542292,3895800075,"PLS Financial Services, Inc.",0.278546,1
29,29,Customer Service Representative- Bilingual Spa...,Consumer Loan Sales Specialist,OneMain Financial,3899542292,3888999967,"PLS Financial Services, Inc.",0.278546,1